server:
  port: 8080

spring:
  datasource:
    username: zhangjingtao
    password: Zhang123
    url: jdbc:mysql://zh-jingtao.mysql.rds.aliyuncs.com:3306/my_test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

#showSql
logging:
  level:
    com:
      example:
        mapper : debug